export default Object.freeze({
    DELETE_TODO:               'DELETE_TODO',
    TOGGLE_COMPLETE_ALL_TODOS: 'TOGGLE_COMPLETE_ALL_TODOS',
    TOGGLE_TODO_PRIORITY:      'TOGGLE_TODO_PRIORITY',
    TOGGLE_COMPLETE_TODO:      'TOGGLE_COMPLETE_TODO',
});
