export default Object.freeze({
    ADD_TODO:         'ADD_TODO',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

    DELETE_TODO: 'DELETE_TODO',

    FETCH_TODOS:         'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',

    TOGGLE_COMPLETE_ALL_TODOS: 'TOGGLE_COMPLETE_ALL_TODOS',
    TOGGLE_TODO_PRIORITY:      'TOGGLE_TODO_PRIORITY',
    TOGGLE_COMPLETE_TODO:      'TOGGLE_COMPLETE_TODO',
    UPDATE_TODO:               'UPDATE_TODO',
});
